apiVersion: v1
kind: Secret
metadata:
  name: redbus-secrets
  namespace: redbus
type: Opaque
stringData:
  POSTGRES_PASSWORD: "123"
  DB_PASSWORD: "123"
  ADMIN_EMAIL: "redbus@example.com"
  ADMIN_PASSWORD: "SecurePassword123!"
  DOCKER_HUB_USERNAME: "bhavy0949"
  DOCKER_HUB_PASSWORD: "your-docker-hub-token"
---
# Secret for Elasticsearch
apiVersion: v1
kind: Secret
metadata:
  name: elk-credentials
  namespace: redbus
type: Opaque
stringData:
  ELASTIC_PASSWORD: "elastic123"
  KIBANA_PASSWORD: "kibana123"
  LOGSTASH_PASSWORD: "logstash123"
