---
- name: Check if minikube is running
  command: minikube status
  changed_when: false
  failed_when: false
  register: minikube_status

- name: Start minikube if not running
  command: minikube start
  when: minikube_status.rc != 0
  changed_when: true

- name: Enable required minikube addons
  command: minikube addons enable {{ item }}
  loop:
    - metrics-server
    - ingress
  changed_when: false

- name: Get Kubernetes cluster info
  command: kubectl cluster-info
  changed_when: false
  register: k8s_info

- name: Display Kubernetes info
  debug:
    msg: "{{ k8s_info.stdout_lines }}"

- name: Get Kubernetes nodes
  command: kubectl get nodes
  changed_when: false
  register: k8s_nodes

- name: Display Kubernetes nodes
  debug:
    msg: "{{ k8s_nodes.stdout }}"
