apiVersion: v1
kind: ConfigMap
metadata:
  name: redbus-config
  namespace: redbus
data:
  EUREKA_SERVER: http://eureka-server:8761/eureka/
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  API_GATEWAY_URL: http://api-gateway:9090
  MEMBER_SERVICE_URL: http://member-service:8081
  SECURITY_SERVICE_URL: http://security-service:8084
  EXPEDITION_SERVICE_URL: http://expedition-service:8082
  PAYMENT_SERVICE_URL: http://payment-service:8083
  FRONTEND_URL: http://localhost:3000
