# --- Application Name ---
spring.application.name=expedition-service
spring.output.ansi.enabled=always

#--- Activate Docker profile ---
spring.profiles.active=docker

# --- Server ---
server.port=8082

# --- JPA Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
